app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('sruju/',sruju,name='sruju'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('manu/',manu,name='manu'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def sruju(request):
    return render(request,'sruju.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def manu(request):
    return render(request,'manu.html')

templates/manu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hello good what about u sruju</h1>
        <a href="{% url 'app1:sruju' %}"><h1>navigate to srujupage</h1></a>
    </center>
    
</body>
</html>

templates/sruju.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi manu how are you</h1>
        <a href="{% url 'app2:manu' %}"><h1>navugate to manupage</h1></a>
      
    </center>
    
</body>
</html>